export const GET_ALL_HOTELS="GET_ALL_HOTELS"
export const GET_ALL_RESTAURANTS="GET_ALL_RESTAURANTS"
export const GET_ALL_HOUSES="GET_ALL_HOUSES"
export const GET_ALL_THINGS="GET_ALL_THINGS"


export const ADD_PRODUCT ="ADD_PRODUCT"
export const TOGGLE_TRUE="TOGGLE_TRUE"
export const TOGGLE_FALSE="TOGGLE_FALSE"
export const GET_ONE_PRODUCT="GET_ONE_PRODUCT"